namespace Blitz3DDecomp;

static class BlitzPlusBuiltIns
{
    public static void Init()
    {
        Function.FromBlitzSymbol("VWait%frames=1");
        Function.FromBlitzSymbol("%ScanLine");
        Function.FromBlitzSymbol("%AvailVidMem");
        Function.FromBlitzSymbol("%TotalVidMem");
        Function.FromBlitzSymbol("%CountGfxDrivers");
        Function.FromBlitzSymbol("$GfxDriverName%driver");
        Function.FromBlitzSymbol("SetGfxDriver%driver");
        Function.FromBlitzSymbol("%CountGfxModes");
        Function.FromBlitzSymbol("%GfxModeWidth%mode");
        Function.FromBlitzSymbol("%GfxModeHeight%mode");
        Function.FromBlitzSymbol("%GfxModeDepth%mode");
        Function.FromBlitzSymbol("%GfxModeFormat%mode");
        Function.FromBlitzSymbol("%GfxModeExists%width%height%depth=0%format=0");
        Function.FromBlitzSymbol("Graphics%width%height%depth=0%flags=0");
        Function.FromBlitzSymbol("EndGraphics");
        Function.FromBlitzSymbol("%BackBuffer");
        Function.FromBlitzSymbol("%FrontBuffer");
        Function.FromBlitzSymbol("%SetBuffer%buffer");
        Function.FromBlitzSymbol("%GraphicsBuffer");
        Function.FromBlitzSymbol("%DesktopBuffer");
        Function.FromBlitzSymbol("%LoadBuffer%buffer$file");
        Function.FromBlitzSymbol("%SaveBuffer%buffer$file");
        Function.FromBlitzSymbol("%GraphicsWidth");
        Function.FromBlitzSymbol("%GraphicsHeight");
        Function.FromBlitzSymbol("%GraphicsDepth");
        Function.FromBlitzSymbol("%GraphicsFormat");
        Function.FromBlitzSymbol("Flip%vwait=1");
        Function.FromBlitzSymbol("LockBuffer%buffer=0");
        Function.FromBlitzSymbol("UnlockBuffer%buffer=0");
        Function.FromBlitzSymbol("%LockedPitch%buffer=0");
        Function.FromBlitzSymbol("%LockedFormat%buffer=0");
        Function.FromBlitzSymbol("%LockedPixels%buffer=0");
        Function.FromBlitzSymbol("%ReadPixel%x%y%buffer=0");
        Function.FromBlitzSymbol("%ReadPixelFast%x%y%buffer=0");
        Function.FromBlitzSymbol("WritePixel%x%y%color%buffer=0");
        Function.FromBlitzSymbol("WritePixelFast%x%y%color%buffer=0");
        Function.FromBlitzSymbol("CopyPixel%src_x%src_y%src_buffer%dst_x%dst_y%dst_buffer=0");
        Function.FromBlitzSymbol("CopyPixelFast%src_x%src_y%src_buffer%dst_x%dst_y%dst_buffer=0");
        Function.FromBlitzSymbol("CopyRect%source_x%source_y%width%height%dest_x%dest_y%source_buffer=0%dest_buffer=0");
        Function.FromBlitzSymbol("%CreateCanvas%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("%CanvasBuffer%canvas");
        Function.FromBlitzSymbol("FlipCanvas%canvas%vwait=0");
        Function.FromBlitzSymbol("Color%red%green%blue");
        Function.FromBlitzSymbol("ClsColor%red%green%blue");
        Function.FromBlitzSymbol("SetFont%font");
        Function.FromBlitzSymbol("Origin%x%y");
        Function.FromBlitzSymbol("Viewport%x%y%width%height");
        Function.FromBlitzSymbol("Cls");
        Function.FromBlitzSymbol("Plot%x%y");
        Function.FromBlitzSymbol("Line%x1%y1%x2%y2");
        Function.FromBlitzSymbol("Rect%x%y%width%height%solid=1");
        Function.FromBlitzSymbol("Oval%x%y%width%height%solid=1");
        Function.FromBlitzSymbol("Text%x%y$text%center_x=0%center_y=0");
        Function.FromBlitzSymbol("GetColor%x%y");
        Function.FromBlitzSymbol("%ColorRed");
        Function.FromBlitzSymbol("%ColorGreen");
        Function.FromBlitzSymbol("%ColorBlue");
        Function.FromBlitzSymbol("%StringWidth$str");
        Function.FromBlitzSymbol("%StringHeight$str");
        Function.FromBlitzSymbol("%FontWidth");
        Function.FromBlitzSymbol("%FontHeight");
        Function.FromBlitzSymbol("%OpenMovie$file");
        Function.FromBlitzSymbol("CloseMovie%movie");
        Function.FromBlitzSymbol("%MovieWidth%movie");
        Function.FromBlitzSymbol("%MovieHeight%movie");
        Function.FromBlitzSymbol("%MoviePlaying%movie");
        Function.FromBlitzSymbol("%DrawMovie%movie%x%y%width=-1%height=-1");
        Function.FromBlitzSymbol("%MouseX%canvas=0");
        Function.FromBlitzSymbol("%MouseY%canvas=0");
        Function.FromBlitzSymbol("%MouseXSpeed%canvas=0");
        Function.FromBlitzSymbol("%MouseYSpeed%canvas=0");
        Function.FromBlitzSymbol("MoveMouse%x%y%canvas=0");
        Function.FromBlitzSymbol("ShowPointer%canvas=0");
        Function.FromBlitzSymbol("HidePointer%canvas=0");
        Function.FromBlitzSymbol("UpdateGamma%calibrate=0");
        Function.FromBlitzSymbol("%GammaGreen%green");
        Function.FromBlitzSymbol("SetGamma%src_red%src_green%src_blue%dest_red%dest_green%dest_blue");
        Function.FromBlitzSymbol("%GammaRed%red");
        Function.FromBlitzSymbol("%GammaBlue%blue");
        Function.FromBlitzSymbol("%LoadImage$file%flags=1");
        Function.FromBlitzSymbol("%LoadAnimImage$file%width%height%first%count%flags=1");
        Function.FromBlitzSymbol("%CreateImage%width%height%frames=1%flags=2");
        Function.FromBlitzSymbol("%CopyImage%image");
        Function.FromBlitzSymbol("FreeImage%image");
        Function.FromBlitzSymbol("MaskImage%image%red%green%blue");
        Function.FromBlitzSymbol("HandleImage%image%handle_x%handle_y");
        Function.FromBlitzSymbol("MidHandle%image");
        Function.FromBlitzSymbol("AutoMidHandle%enable");
        Function.FromBlitzSymbol("%ImageWidth%image");
        Function.FromBlitzSymbol("%ImageHeight%image");
        Function.FromBlitzSymbol("%ImageXHandle%image");
        Function.FromBlitzSymbol("%ImageYHandle%image");
        Function.FromBlitzSymbol("%ImageBuffer%image%frame=0");
        Function.FromBlitzSymbol("%SaveImage%image$file%frame=0");
        Function.FromBlitzSymbol("TFormFilter%enable");
        Function.FromBlitzSymbol("TFormImage%image#a#b#c#d");
        Function.FromBlitzSymbol("ScaleImage%image#xscale#yscale");
        Function.FromBlitzSymbol("ResizeImage%image#width#height");
        Function.FromBlitzSymbol("RotateImage%image#angle");
        Function.FromBlitzSymbol("DrawImage%image%x%y%frame=0");
        Function.FromBlitzSymbol("DrawBlock%image%x%y%frame=0");
        Function.FromBlitzSymbol("TileImage%image%x=0%y=0%frame=0");
        Function.FromBlitzSymbol("TileBlock%image%x=0%y=0%frame=0");
        Function.FromBlitzSymbol("GrabImage%image%x%y%frame=0");
        Function.FromBlitzSymbol("DrawImageRect%image%x%y%rect_x%rect_y%rect_width%rect_height%frame=0");
        Function.FromBlitzSymbol("DrawBlockRect%image%x%y%rect_x%rect_y%rect_width%rect_height%frame=0");
        Function.FromBlitzSymbol("%RectsOverlap%x1%y1%width1%height1%x2%y2%width2%height2");
        Function.FromBlitzSymbol("%ImagesOverlap%image1%x1%y1%image2%x2%y2");
        Function.FromBlitzSymbol("%ImagesCollide%image1%x1%y1%frame1%image2%x2%y2%frame2");
        Function.FromBlitzSymbol("%PeekEvent");
        Function.FromBlitzSymbol("%ImageRectOverlap%image%x%y%rect_x%rect_y%rect_width%rect_height");
        Function.FromBlitzSymbol("%WaitEvent%timeout=-1");
        Function.FromBlitzSymbol("%EventID");
        Function.FromBlitzSymbol("%ImageRectCollide%image%x%y%frame%rect_x%rect_y%rect_width%rect_height");
        Function.FromBlitzSymbol("%EventData");
        Function.FromBlitzSymbol("%EventX");
        Function.FromBlitzSymbol("%EventY");
        Function.FromBlitzSymbol("%EventZ");
        Function.FromBlitzSymbol("%EventSource");
        Function.FromBlitzSymbol("%KeyDown%keycode");
        Function.FromBlitzSymbol("%KeyHit%keycode");
        Function.FromBlitzSymbol("%GetKey");
        Function.FromBlitzSymbol("%WaitKey");
        Function.FromBlitzSymbol("%KeyWait");
        Function.FromBlitzSymbol("FlushKeys");
        Function.FromBlitzSymbol("%MouseZ");
        Function.FromBlitzSymbol("%MouseZSpeed");
        Function.FromBlitzSymbol("%MouseDown%button");
        Function.FromBlitzSymbol("%MouseHit%button");
        Function.FromBlitzSymbol("%GetMouse");
        Function.FromBlitzSymbol("%WaitMouse");
        Function.FromBlitzSymbol("%MouseWait");
        Function.FromBlitzSymbol("FlushMouse");
        Function.FromBlitzSymbol("RuntimeStats");
        Function.FromBlitzSymbol("FreeGadget%gadget");
        Function.FromBlitzSymbol("SetGadgetFont%gadget%font");
        Function.FromBlitzSymbol("SetGadgetText%gadget$text");
        Function.FromBlitzSymbol("SetGadgetShape%gadget%x%y%width%height");
        Function.FromBlitzSymbol("SetGadgetLayout%gadget%left%right%top%bottom");
        Function.FromBlitzSymbol("ShowGadget%gadget");
        Function.FromBlitzSymbol("HideGadget%gadget");
        Function.FromBlitzSymbol("EnableGadget%gadget");
        Function.FromBlitzSymbol("DisableGadget%gadget");
        Function.FromBlitzSymbol("ActivateGadget%gadget");
        Function.FromBlitzSymbol("%GadgetFont%gadget");
        Function.FromBlitzSymbol("$GadgetText%gadget");
        Function.FromBlitzSymbol("%GadgetX%gadget");
        Function.FromBlitzSymbol("%GadgetY%gadget");
        Function.FromBlitzSymbol("%GadgetWidth%gadget");
        Function.FromBlitzSymbol("%GadgetHeight%gadget");
        Function.FromBlitzSymbol("%GadgetGroup%gadget");
        Function.FromBlitzSymbol("%ClientWidth%group");
        Function.FromBlitzSymbol("%ClientHeight%group");
        Function.FromBlitzSymbol("%CreateMenu$text%menu_id%parent_menu");
        Function.FromBlitzSymbol("SetMenuText%menu$text");
        Function.FromBlitzSymbol("CheckMenu%menu");
        Function.FromBlitzSymbol("UncheckMenu%menu");
        Function.FromBlitzSymbol("EnableMenu%menu");
        Function.FromBlitzSymbol("DisableMenu%menu");
        Function.FromBlitzSymbol("%MenuChecked%menu");
        Function.FromBlitzSymbol("%MenuEnabled%menu");
        Function.FromBlitzSymbol("$MenuText%menu");
        Function.FromBlitzSymbol("%LoadIconStrip$file");
        Function.FromBlitzSymbol("FreeIconStrip%icon_strip");
        Function.FromBlitzSymbol("SetGadgetIconStrip%gadget%icon_strip");
        Function.FromBlitzSymbol("%CreateLabel$text%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("%CreateButton$text%x%y%width%height%group%style=1");
        Function.FromBlitzSymbol("SetButtonState%button%state");
        Function.FromBlitzSymbol("%ButtonState%button");
        Function.FromBlitzSymbol("%CreateTextField%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("$TextFieldText%textfield");
        Function.FromBlitzSymbol("%CreateComboBox%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("%CreateListBox%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("%CreateTreeView%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("%TreeViewRoot%treeview");
        Function.FromBlitzSymbol("%SelectedTreeViewNode%treeview");
        Function.FromBlitzSymbol("%CountTreeViewNodes%parent_node");
        Function.FromBlitzSymbol("%AddTreeViewNode$text%parent_node%icon=-1");
        Function.FromBlitzSymbol("%InsertTreeViewNode%index$text%parent_node%icon=-1");
        Function.FromBlitzSymbol("ModifyTreeViewNode%node$text%icon=-1");
        Function.FromBlitzSymbol("SelectTreeViewNode%node");
        Function.FromBlitzSymbol("ExpandTreeViewNode%node");
        Function.FromBlitzSymbol("CollapseTreeViewNode%node");
        Function.FromBlitzSymbol("FreeTreeViewNode%node");
        Function.FromBlitzSymbol("$TreeViewNodeText%node");
        Function.FromBlitzSymbol("%CreateProgBar%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("UpdateProgBar%progbar#progress");
        Function.FromBlitzSymbol("%CreateSlider%x%y%width%height%group%style=1");
        Function.FromBlitzSymbol("SetSliderRange%slider%visible%total");
        Function.FromBlitzSymbol("SetSliderValue%slider%value");
        Function.FromBlitzSymbol("%SliderValue%slider");
        Function.FromBlitzSymbol("%CreateWindow$text%x%y%width%height%group=0%style=15");
        Function.FromBlitzSymbol("%ActiveWindow");
        Function.FromBlitzSymbol("ActivateWindow%window");
        Function.FromBlitzSymbol("UpdateWindowMenu%window");
        Function.FromBlitzSymbol("%SetStatusText%window$text");
        Function.FromBlitzSymbol("SetMinWindowSize%window%width=-1%height=-1");
        Function.FromBlitzSymbol("MinimizeWindow%window");
        Function.FromBlitzSymbol("MaximizeWindow%window");
        Function.FromBlitzSymbol("RestoreWindow%window");
        Function.FromBlitzSymbol("%WindowMinimized%window");
        Function.FromBlitzSymbol("%WindowMaximized%window");
        Function.FromBlitzSymbol("%WindowMenu%window");
        Function.FromBlitzSymbol("%CreateTabber%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("%CreatePanel%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("SetPanelImage%panel$file");
        Function.FromBlitzSymbol("SetPanelColor%panel%red%green%blue");
        Function.FromBlitzSymbol("%CreateTextArea%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("SetTextAreaTabs%textarea%tabs");
        Function.FromBlitzSymbol("SetTextAreaFont%textarea%font");
        Function.FromBlitzSymbol("SetTextAreaColor%textarea%red%green%blue%background=0");
        Function.FromBlitzSymbol("%TextAreaLen%textarea%units=1");
        Function.FromBlitzSymbol("%TextAreaLineLen%textarea%line");
        Function.FromBlitzSymbol("%TextAreaChar%textarea%line");
        Function.FromBlitzSymbol("%TextAreaLine%textarea%char");
        Function.FromBlitzSymbol("%TextAreaCursor%textarea%units=1");
        Function.FromBlitzSymbol("%TextAreaSelLen%textarea%units=1");
        Function.FromBlitzSymbol("AddTextAreaText%textarea$text");
        Function.FromBlitzSymbol("SetTextAreaText%textarea$text%pos=0%len=-1%units=1");
        Function.FromBlitzSymbol("FormatTextAreaText%textarea%red%green%blue%flags%pos=0%len=-1%units=1");
        Function.FromBlitzSymbol("$TextAreaText%textarea%pos=0%len=-1%units=1");
        Function.FromBlitzSymbol("LockTextArea%textarea");
        Function.FromBlitzSymbol("UnlockTextArea%textarea");
        Function.FromBlitzSymbol("%CreateToolBar$icons%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("EnableToolBarItem%toolbar%index");
        Function.FromBlitzSymbol("DisableToolBarItem%toolbar%index");
        Function.FromBlitzSymbol("SetToolBarTips%toolbar$tips");
        Function.FromBlitzSymbol("%CreateHtmlView%x%y%width%height%group%style=0");
        Function.FromBlitzSymbol("HtmlViewGo%htmlview$URL");
        Function.FromBlitzSymbol("HtmlViewRun%htmlview$URL");
        Function.FromBlitzSymbol("HtmlViewBack%htmlview");
        Function.FromBlitzSymbol("HtmlViewForward%htmlview");
        Function.FromBlitzSymbol("%HtmlViewStatus%htmlview");
        Function.FromBlitzSymbol("$HtmlViewCurrentURL%htmlview");
        Function.FromBlitzSymbol("$HtmlViewEventURL%htmlview");
        Function.FromBlitzSymbol("%Desktop");
        Function.FromBlitzSymbol("ClearGadgetItems%gadget");
        Function.FromBlitzSymbol("AddGadgetItem%gadget$item%select=0%icon=-1");
        Function.FromBlitzSymbol("InsertGadgetItem%gadget%index$item%icon=-1");
        Function.FromBlitzSymbol("ModifyGadgetItem%gadget%index$item%icon=-1");
        Function.FromBlitzSymbol("RemoveGadgetItem%gadget%index");
        Function.FromBlitzSymbol("SelectGadgetItem%gadget%index");
        Function.FromBlitzSymbol("$GadgetItemText%gadget%index");
        Function.FromBlitzSymbol("%CountGadgetItems%gadget");
        Function.FromBlitzSymbol("%SelectedGadgetItem%gadget");
        Function.FromBlitzSymbol("%RequestFont");
        Function.FromBlitzSymbol("%RequestColor%red=255%green=255%blue=255");
        Function.FromBlitzSymbol("%RequestedRed");
        Function.FromBlitzSymbol("%RequestedGreen");
        Function.FromBlitzSymbol("%RequestedBlue");
        Function.FromBlitzSymbol("$RequestDir$prompt=\"\"$path=\"\"");
        Function.FromBlitzSymbol("$RequestFile$prompt=\"\"$exts=\"\"%save=0$defname=\"\"");
        Function.FromBlitzSymbol("%ExecFile$file");
        Function.FromBlitzSymbol("$GetEnv$var");
        Function.FromBlitzSymbol("SetEnv$var$value");
        Function.FromBlitzSymbol("$CommandLine");
        Function.FromBlitzSymbol("Write$text");
        Function.FromBlitzSymbol("Print$text");
        Function.FromBlitzSymbol("RuntimeError$error");
        Function.FromBlitzSymbol("$Input$prompt=\"\"");
        Function.FromBlitzSymbol("Notify$text%serious=0");
        Function.FromBlitzSymbol("%Confirm$text%serious=0");
        Function.FromBlitzSymbol("%Proceed$text%serious=0");
        Function.FromBlitzSymbol("AppTitle$str");
        Function.FromBlitzSymbol("$SystemProperty$property");
        Function.FromBlitzSymbol("End");
        Function.FromBlitzSymbol("DebugObjects");
        Function.FromBlitzSymbol("%ActiveObjects");
        Function.FromBlitzSymbol("%QueryObject%object%query_id");
        Function.FromBlitzSymbol("Stop");
        Function.FromBlitzSymbol("DebugLog$message");
        Function.FromBlitzSymbol("_bbDebugStmt");
        Function.FromBlitzSymbol("_bbDebugEnter");
        Function.FromBlitzSymbol("_bbDebugLeave");
        Function.FromBlitzSymbol("#Sin#degrees");
        Function.FromBlitzSymbol("#Cos#degrees");
        Function.FromBlitzSymbol("#Tan#degrees");
        Function.FromBlitzSymbol("#ASin#float");
        Function.FromBlitzSymbol("#ACos#float");
        Function.FromBlitzSymbol("#ATan#float");
        Function.FromBlitzSymbol("#ATan2#floata#floatb");
        Function.FromBlitzSymbol("#Sqr#float");
        Function.FromBlitzSymbol("#Floor#float");
        Function.FromBlitzSymbol("#Ceil#float");
        Function.FromBlitzSymbol("#Exp#float");
        Function.FromBlitzSymbol("#Log#float");
        Function.FromBlitzSymbol("#Log10#float");
        Function.FromBlitzSymbol("#Rnd#from#to=0");
        Function.FromBlitzSymbol("%Rand%from%to=1");
        Function.FromBlitzSymbol("SeedRnd%seed");
        Function.FromBlitzSymbol("%RndSeed");
        Function.FromBlitzSymbol("$String$string%repeat");
        Function.FromBlitzSymbol("$Left$string%count");
        Function.FromBlitzSymbol("$Right$string%count");
        Function.FromBlitzSymbol("$Replace$string$from$to");
        Function.FromBlitzSymbol("%Instr$string$find%from=1");
        Function.FromBlitzSymbol("$Mid$string%start%count=-1");
        Function.FromBlitzSymbol("$Upper$string");
        Function.FromBlitzSymbol("$Lower$string");
        Function.FromBlitzSymbol("$Trim$string");
        Function.FromBlitzSymbol("$LSet$string%size");
        Function.FromBlitzSymbol("$RSet$string%size");
        Function.FromBlitzSymbol("$Chr%ascii");
        Function.FromBlitzSymbol("%Asc$string");
        Function.FromBlitzSymbol("%Len$string");
        Function.FromBlitzSymbol("$Hex%value");
        Function.FromBlitzSymbol("$Bin%value");
        Function.FromBlitzSymbol("%CreateBank%size=0");
        Function.FromBlitzSymbol("FreeBank%bank");
        Function.FromBlitzSymbol("%BankSize%bank");
        Function.FromBlitzSymbol("ResizeBank%bank%size");
        Function.FromBlitzSymbol("CopyBank%src_bank%src_offset%dest_bank%dest_offset%count");
        Function.FromBlitzSymbol("%PeekByte%bank%offset");
        Function.FromBlitzSymbol("%PeekShort%bank%offset");
        Function.FromBlitzSymbol("%PeekInt%bank%offset");
        Function.FromBlitzSymbol("#PeekFloat%bank%offset");
        Function.FromBlitzSymbol("PokeByte%bank%offset%value");
        Function.FromBlitzSymbol("PokeShort%bank%offset%value");
        Function.FromBlitzSymbol("PokeInt%bank%offset%value");
        Function.FromBlitzSymbol("PokeFloat%bank%offset#value");
        Function.FromBlitzSymbol("%ReadBytes%bank%file%offset%count");
        Function.FromBlitzSymbol("%WriteBytes%bank%file%offset%count");
        Function.FromBlitzSymbol("%CallDLL$dll_name$func_name%in_bank=0%out_bank=0");
        Function.FromBlitzSymbol("AutoSuspend%enable");
        Function.FromBlitzSymbol("FlushEvents%kind=-1%source=0");
        Function.FromBlitzSymbol("HotKeyEvent%rawkey%modifier%ev_id%ev_data=0%ev_x=0%ev_y=0%ev_z=0%ev_source=0");
        Function.FromBlitzSymbol("%Eof%stream");
        Function.FromBlitzSymbol("%ReadAvail%stream");
        Function.FromBlitzSymbol("%ReadByte%stream");
        Function.FromBlitzSymbol("%ReadShort%stream");
        Function.FromBlitzSymbol("%ReadInt%stream");
        Function.FromBlitzSymbol("#ReadFloat%stream");
        Function.FromBlitzSymbol("$ReadString%stream");
        Function.FromBlitzSymbol("$ReadLine%stream");
        Function.FromBlitzSymbol("WriteByte%stream%byte");
        Function.FromBlitzSymbol("WriteShort%stream%short");
        Function.FromBlitzSymbol("WriteInt%stream%int");
        Function.FromBlitzSymbol("WriteFloat%stream#float");
        Function.FromBlitzSymbol("WriteString%stream$string");
        Function.FromBlitzSymbol("WriteLine%stream$string");
        Function.FromBlitzSymbol("CopyStream%src_stream%dest_stream%buffer_size=16384");
        Function.FromBlitzSymbol("%OpenFile$filename");
        Function.FromBlitzSymbol("%ReadFile$filename");
        Function.FromBlitzSymbol("%WriteFile$filename");
        Function.FromBlitzSymbol("CloseFile%file_stream");
        Function.FromBlitzSymbol("%FilePos%file_stream");
        Function.FromBlitzSymbol("%SeekFile%file_stream%pos");
        Function.FromBlitzSymbol("%FileSize$file");
        Function.FromBlitzSymbol("%FileType$file");
        Function.FromBlitzSymbol("CopyFile$file$to");
        Function.FromBlitzSymbol("DeleteFile$file");
        Function.FromBlitzSymbol("%ReadDir$dirname");
        Function.FromBlitzSymbol("CloseDir%dir");
        Function.FromBlitzSymbol("%MoreFiles%dir");
        Function.FromBlitzSymbol("$NextFile%dir");
        Function.FromBlitzSymbol("$CurrentDir");
        Function.FromBlitzSymbol("ChangeDir$dir");
        Function.FromBlitzSymbol("CreateDir$dir");
        Function.FromBlitzSymbol("DeleteDir$dir");
        Function.FromBlitzSymbol("%MilliSecs");
        Function.FromBlitzSymbol("Delay%millisecs");
        Function.FromBlitzSymbol("$CurrentDate");
        Function.FromBlitzSymbol("$CurrentTime");
        Function.FromBlitzSymbol("%CreateTimer#hertz");
        Function.FromBlitzSymbol("FreeTimer%timer");
        Function.FromBlitzSymbol("%TimerTicks%timer");
        Function.FromBlitzSymbol("%WaitTimer%timer");
        Function.FromBlitzSymbol("ResetTimer%timer");
        Function.FromBlitzSymbol("PauseTimer%timer");
        Function.FromBlitzSymbol("ResumeTimer%timer");
        Function.FromBlitzSymbol("%CreateProcess$command");
        Function.FromBlitzSymbol("%LoadFont$fontname%height%bold=0%italic=0%underline=0");
        Function.FromBlitzSymbol("FreeFont%font");
        Function.FromBlitzSymbol("$FontName%font");
        Function.FromBlitzSymbol("%FontSize%font");
        Function.FromBlitzSymbol("%FontStyle%font");
        Function.FromBlitzSymbol("%FontAscent%font");
        Function.FromBlitzSymbol("%FontDescent%font");
        Function.FromBlitzSymbol("$DottedIP%IP");
        Function.FromBlitzSymbol("%CountHostIPs$host_name");
        Function.FromBlitzSymbol("%HostIP%host_index");
        Function.FromBlitzSymbol("%CreateUDPStream%port=0");
        Function.FromBlitzSymbol("CloseUDPStream%udp_stream");
        Function.FromBlitzSymbol("SendUDPMsg%udp_stream%dest_ip%dest_port=0");
        Function.FromBlitzSymbol("%RecvUDPMsg%udp_stream");
        Function.FromBlitzSymbol("%UDPStreamIP%udp_stream");
        Function.FromBlitzSymbol("%UDPStreamPort%udp_stream");
        Function.FromBlitzSymbol("%UDPMsgIP%udp_stream");
        Function.FromBlitzSymbol("%UDPMsgPort%udp_stream");
        Function.FromBlitzSymbol("UDPTimeouts%recv_timeout");
        Function.FromBlitzSymbol("%OpenTCPStream$server%server_port%local_port=0");
        Function.FromBlitzSymbol("CloseTCPStream%tcp_stream");
        Function.FromBlitzSymbol("%CreateTCPServer%port");
        Function.FromBlitzSymbol("CloseTCPServer%tcp_server");
        Function.FromBlitzSymbol("%AcceptTCPStream%tcp_server");
        Function.FromBlitzSymbol("%TCPStreamIP%tcp_stream");
        Function.FromBlitzSymbol("%TCPStreamPort%tcp_stream");
        Function.FromBlitzSymbol("TCPTimeouts%read_millis%accept_millis");
        Function.FromBlitzSymbol("%LoadSound$filename");
        Function.FromBlitzSymbol("FreeSound%sound");
        Function.FromBlitzSymbol("LoopSound%sound");
        Function.FromBlitzSymbol("SoundPitch%sound%pitch");
        Function.FromBlitzSymbol("SoundVolume%sound#volume");
        Function.FromBlitzSymbol("SoundPan%sound#pan");
        Function.FromBlitzSymbol("%PlaySound%sound%flags=0");
        Function.FromBlitzSymbol("%PlayMusic$file%flags=0");
        Function.FromBlitzSymbol("%PlayCDTrack%track%flags=0");
        Function.FromBlitzSymbol("StopChannel%channel");
        Function.FromBlitzSymbol("PauseChannel%channel");
        Function.FromBlitzSymbol("ResumeChannel%channel");
        Function.FromBlitzSymbol("ChannelPitch%channel%pitch");
        Function.FromBlitzSymbol("ChannelVolume%channel#volume");
        Function.FromBlitzSymbol("ChannelPan%channel#pan");
        Function.FromBlitzSymbol("%ChannelPlaying%channel");
        Function.FromBlitzSymbol("%JoyType%port=0");
        Function.FromBlitzSymbol("%JoyDown%button%port=0");
        Function.FromBlitzSymbol("%JoyHit%button%port=0");
        Function.FromBlitzSymbol("#JoyX%port=0");
        Function.FromBlitzSymbol("#JoyY%port=0");
        Function.FromBlitzSymbol("#JoyZ%port=0");
        Function.FromBlitzSymbol("#JoyU%port=0");
        Function.FromBlitzSymbol("#JoyV%port=0");
        Function.FromBlitzSymbol("#JoyPitch%port=0");
        Function.FromBlitzSymbol("#JoyYaw%port=0");
        Function.FromBlitzSymbol("#JoyRoll%port=0");
        Function.FromBlitzSymbol("%JoyHat%port=0");
        Function.FromBlitzSymbol("%JoyXDir%port=0");
        Function.FromBlitzSymbol("%JoyYDir%port=0");
        Function.FromBlitzSymbol("%JoyZDir%port=0");
        Function.FromBlitzSymbol("%JoyUDir%port=0");
        Function.FromBlitzSymbol("%JoyVDir%port=0");
        Function.FromBlitzSymbol("FlushJoy");

        _ = new Function("_builtIn__bbAbs", DeclType.Int) { ReturnType = DeclType.Int };
        _ = new Function("_builtIn__bbFAbs", DeclType.Float) { ReturnType = DeclType.Float };
        _ = new Function("_builtIn__bbSgn", DeclType.Int) { ReturnType = DeclType.Int };
        _ = new Function("_builtIn__bbFSgn", DeclType.Float) { ReturnType = DeclType.Float };
        _ = new Function("_builtIn__bbFPow", DeclType.Float, DeclType.Float) { ReturnType = DeclType.Float };
        _ = new Function("_builtIn__bbMod", DeclType.Int, DeclType.Int) { ReturnType = DeclType.Int };
        _ = new Function("_builtIn__bbFMod", DeclType.Float, DeclType.Float) { ReturnType = DeclType.Float };

        _ = new Function("_builtIn__bbInitCStrs", 1);
        _ = new Function("_builtIn__bbStrTmp", DeclType.String) { ReturnType = DeclType.String };
        _ = new Function("_builtIn__bbStrTmpFree", 1);
        _ = new Function("_builtIn__bbIStrTmpFree", DeclType.Int, DeclType.Int) { ReturnType = DeclType.Int };
        _ = new Function("_builtIn__bbStrFTmpFree", DeclType.Float, DeclType.Int) { ReturnType = DeclType.Float };
        _ = new Function("_builtIn__bbStrRetain", DeclType.String) { ReturnType = DeclType.String };
        _ = new Function("_builtIn__bbStrConst", 1) { ReturnType = DeclType.String };
        _ = new Function("_builtIn__bbStrFromInt", DeclType.Int) { ReturnType = DeclType.String };
        _ = new Function("_builtIn__bbStrFromFloat", DeclType.Float) { ReturnType = DeclType.String };
        _ = new Function("_builtIn__bbStrToInt", DeclType.String) { ReturnType = DeclType.Int };
        _ = new Function("_builtIn__bbStrToFloat", DeclType.String) { ReturnType = DeclType.Float };
        _ = new Function("_builtIn__bbStrLoad", DeclType.String) { ReturnType = DeclType.String };
        _ = new Function("_builtIn__bbStrRelease", DeclType.String);
        _ = new Function("_builtIn__bbStrStore", 2);
        _ = new Function("_builtIn__bbStrConcat", DeclType.String, DeclType.String) { ReturnType = DeclType.String };
        _ = new Function("_builtIn__bbStrCompare", DeclType.String, DeclType.String) { ReturnType = DeclType.Int };
        _ = new Function("_builtIn__bbStrToCStr", DeclType.String) { ReturnType = DeclType.String };
        _ = new Function("_builtIn__bbStrFromCStr", DeclType.String) { ReturnType = DeclType.String };

        _ = new Function("_builtIn_ferrorlog", 0) { ReturnType = DeclType.String };

        _ = new Function("_builtIn__bbVecAlloc", 1);
        _ = new Function("_builtIn__bbVecFree", 2);

        _ = new Function("_builtIn__bbRestore", 1);
        _ = new Function("_builtIn__bbReadInt", 0);
        _ = new Function("_builtIn__bbReadFloat", 0);
        _ = new Function("_builtIn__bbReadStr", 0);

        _ = new Function("_builtIn__bbLoadLibs", 1);

        _ = new Function("_builtIn__bbObjEachFirst", 2);
        _ = new Function("_builtIn__bbObjEachNext", 1);
        _ = new Function("_builtIn__bbObjEachFirst2", 2);
        _ = new Function("_builtIn__bbObjEachNext2", 1);
        _ = new Function("_builtIn__bbObjFromHandle", DeclType.Int, DeclType.Unknown);
        _ = new Function("_builtIn__bbObjToHandle", 1) { ReturnType = DeclType.Int };
        _ = new Function("_builtIn__bbObjNew", 1);
        _ = new Function("_builtIn__bbObjNext", 1);
        _ = new Function("_builtIn__bbObjPrev", 1);
        _ = new Function("_builtIn__bbObjCompare", 2);
        _ = new Function("_builtIn__bbObjRelease", 1);
        _ = new Function("_builtIn__bbObjStore", 2);
        _ = new Function("_builtIn__bbObjLoad", 1);
        _ = new Function("_builtIn__bbFieldPtrAdd", 2);
        _ = new Function("_builtIn__bbObjDelete", 1);

        _ = new Function("_builtIn__bbDimArray", 1);
        _ = new Function("_builtIn__bbUndimArray", 1);
    }
}